added logic timeout for wget command
added logic timeout for wget command and if metadata prop is 0 size then don't run the startscript

i.e. /usr/bin/wget --quiet --no-proxy --tries=2 --timeout=1 -O $FENCE_TXT  http://secmon2.wdf.sap.corp:8887

diff --git a/SequencialStopStartLogic b/SequencialStopStartLogic
--- a/SequencialStopStartLogic
+++ b/SequencialStopStartLogic
@@ -137,25 +137,29 @@ function WhereAreWe {
     local BASH_MD_PROP="$WORK/md.sh"
     test -f $MD_PROP && rm -f  $MD_PROP
     unset http_proxy
-    /usr/bin/wget --quiet -O $MD_PROP  http://secmon-ipcheck.wdf.sap.corp:8887
+    /usr/bin/wget --quiet --tries=2 --timeout=1 -O $MD_PROP  http://secmon-ipcheck.wdf.sap.corp:8887
     if [ ! -s $MD_PROP ]; then
-        /usr/bin/wget --quiet -O $MD_PROP  http://secmon2.wdf.sap.corp:8887
+        /usr/bin/wget --quiet --tries=2 --timeout=1 -O $MD_PROP  http://secmon2.wdf.sap.corp:8887
     fi
     if [ ! -s $MD_PROP ]; then
         rm -f $MD_PROP
-        /usr/bin/wget --quiet -O $MD_PROP http://secmon-trans-dmz.dmzwdf.sap.corp:8887
+        /usr/bin/wget --quiet --tries=2 --timeout=1 -O $MD_PROP http://secmon-trans-dmz.dmzwdf.sap.corp:8887
         /usr/bin/dos2unix $MD_PROP
         rm -f $BASH_MD_PROP
         cat $MD_PROP > $BASH_MD_PROP
         source $BASH_MD_PROP
     else
         test -f  $FENCE_TXT && rm -f $FENCE_TXT
-        /usr/bin/wget --quiet -O $FENCE_TXT  http://secmon2.wdf.sap.corp:8887
+        /usr/bin/wget --quiet --tries=2 --timeout=1 -O $FENCE_TXT  http://secmon2.wdf.sap.corp:8887
         /usr/bin/dos2unix $MD_PROP
         /usr/bin/dos2unix $FENCE_TXT
         rm -f $BASH_MD_PROP
         cat $MD_PROP > $BASH_MD_PROP
         source $BASH_MD_PROP
+    fi
+    if [ ! -s $MD_PROP ]; then
+        echo "cannot get metaData prop through secmon tomcat service - no master detected - will not proceed with any start logic. Exiting..."
+        exit 1
     fi
 
     unset SHOWROOM
